output "vpc_id" {
  description = "CommerceLink VPC ID."
  value       = aws_vpc.this.id
}

output "public_subnet_ids" {
  description = "Public subnet IDs."
  value       = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  description = "Private subnet IDs."
  value       = aws_subnet.private[*].id
}

output "beanstalk_application_name" {
  description = "Elastic Beanstalk application name."
  value       = aws_elastic_beanstalk_application.app.name
}

output "beanstalk_environment_name" {
  description = "Elastic Beanstalk environment name."
  value       = aws_elastic_beanstalk_environment.app.name
}

output "beanstalk_endpoint_url" {
  description = "Elastic Beanstalk environment endpoint."
  value       = aws_elastic_beanstalk_environment.app.endpoint_url
}

output "s3_bucket_names" {
  description = "Application S3 bucket names."
  value       = { for name, bucket in aws_s3_bucket.app : name => bucket.bucket }
}

output "sqs_queue_urls" {
  description = "Application SQS queue URLs."
  value       = { for name, queue in aws_sqs_queue.app : name => queue.url }
}

output "sqs_dead_letter_queue_urls" {
  description = "Application SQS dead-letter queue URLs."
  value       = { for name, queue in aws_sqs_queue.dlq : name => queue.url }
}

output "cognito_user_pool_id" {
  description = "Cognito user pool ID."
  value       = aws_cognito_user_pool.app.id
}

output "cognito_user_pool_client_id" {
  description = "Cognito app client ID."
  value       = aws_cognito_user_pool_client.app.id
}

output "valkey_endpoint_parameter_name" {
  description = "SSM parameter name containing the Valkey primary endpoint."
  value       = aws_ssm_parameter.valkey_endpoint.name
}

output "valkey_auth_secret_name" {
  description = "Secrets Manager secret name containing the Valkey AUTH token."
  value       = aws_secretsmanager_secret.valkey_auth_token.name
}

output "api_gateway_invoke_url" {
  description = "API Gateway invoke URL."
  value       = var.enable_api_gateway ? aws_api_gateway_stage.app[0].invoke_url : null
}

output "route53_zone_id" {
  description = "Route53 hosted zone ID used for CommerceLink DNS records."
  value       = local.route53_zone_id
}

output "route53_zone_name" {
  description = "Route53 hosted zone name created by this configuration, when route53_zone_name is set."
  value       = var.route53_zone_name
}

output "route53_zone_name_servers" {
  description = "Name servers for the created Route53 hosted zone. Add these as NS records at the parent domain registrar/DNS provider."
  value       = var.route53_zone_name != null ? aws_route53_zone.this[0].name_servers : null
}

output "acm_certificate_arn" {
  description = "ACM certificate ARN used for HTTPS, either provided or created by this configuration."
  value       = local.acm_certificate_arn
}

output "app_environment" {
  description = "Application environment variables generated by Terraform."
  value       = local.app_environment
  sensitive   = true
}
